### ISSUE TITLE
Некорректный ответ на задание

### ISSUE THREAD

**Issue by alterwalker** [delongerr/geekuniversity#1]
// Потому что статические переменные принадлежат классу, а не объекту

Не совсем, переменные в этих примерах принадлежат методу, который принадлежит классу. Из твоего ответа следует, что такой код будет увеличивать значение $x дальше
```
class A {
    public function foo() {
        static $x = 0;
        echo ++$x;
    }
    public function bar() {
        static $x = 0;
        echo ++$x;
    }
}
$a1 = new A();
$a2 = new A();
$a1->foo(); // 1
$a2->foo(); // 2
$a1->foo(); // 3
$a2->foo(); // 4
$a1->bar(); // 5?
$a2->bar(); 
$a2->bar();
$a2->bar();
```

**Comment by delongerr** [comment]
Не следует, понял теперь в чем ошибка
